// Code generated by MockGen. DO NOT EDIT.
// Source: service/foo.go

// Package mock_xxxservice is a generated GoMock package.
package mock_xxxservice

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockXxxService is a mock of XxxService interface.
type MockXxxService struct {
	ctrl     *gomock.Controller
	recorder *MockXxxServiceMockRecorder
}

// MockXxxServiceMockRecorder is the mock recorder for MockXxxService.
type MockXxxServiceMockRecorder struct {
	mock *MockXxxService
}

// NewMockXxxService creates a new mock instance.
func NewMockXxxService(ctrl *gomock.Controller) *MockXxxService {
	mock := &MockXxxService{ctrl: ctrl}
	mock.recorder = &MockXxxServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockXxxService) EXPECT() *MockXxxServiceMockRecorder {
	return m.recorder
}

// Xxx mocks base method.
func (m *MockXxxService) Xxx() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Xxx")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Xxx indicates an expected call of Xxx.
func (mr *MockXxxServiceMockRecorder) Xxx() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Xxx", reflect.TypeOf((*MockXxxService)(nil).Xxx))
}
