// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package xxxservice

import (
	"sync"
)

// Ensure, that XxxServiceMock does implement XxxService.
// If this is not the case, regenerate this file with moq.
var _ XxxService = &XxxServiceMock{}

// XxxServiceMock is a mock implementation of XxxService.
//
//	func TestSomethingThatUsesXxxService(t *testing.T) {
//
//		// make and configure a mocked XxxService
//		mockedXxxService := &XxxServiceMock{
//			XxxFunc: func() bool {
//				panic("mock out the Xxx method")
//			},
//		}
//
//		// use mockedXxxService in code that requires XxxService
//		// and then make assertions.
//
//	}
type XxxServiceMock struct {
	// XxxFunc mocks the Xxx method.
	XxxFunc func() bool

	// calls tracks calls to the methods.
	calls struct {
		// Xxx holds details about calls to the Xxx method.
		Xxx []struct {
		}
	}
	lockXxx sync.RWMutex
}

// Xxx calls XxxFunc.
func (mock *XxxServiceMock) Xxx() bool {
	if mock.XxxFunc == nil {
		panic("XxxServiceMock.XxxFunc: method is nil but XxxService.Xxx was just called")
	}
	callInfo := struct {
	}{}
	mock.lockXxx.Lock()
	mock.calls.Xxx = append(mock.calls.Xxx, callInfo)
	mock.lockXxx.Unlock()
	return mock.XxxFunc()
}

// XxxCalls gets all the calls that were made to Xxx.
// Check the length with:
//
//	len(mockedXxxService.XxxCalls())
func (mock *XxxServiceMock) XxxCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockXxx.RLock()
	calls = mock.calls.Xxx
	mock.lockXxx.RUnlock()
	return calls
}
